GET http://localhost:3000/users
###

GET http://localhost:3000/users/5eb8fcfa1dc2d021687c2658
###

POST http://localhost:3000/users/
Content-Type: application/json

{
    "name": "Anders",
    "email": "anders_soderberg@hotmail.com"
}
###

DELETE http://localhost:3000/users/5eb8ef3f07205d06d8afb874
###

PATCH http://localhost:3000/users/5eb8fcfa1dc2d021687c2658
Content-Type: application/json

{
    "email": "anders_soderberg@hotmail.com"
}